exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock

collections:
  # 槽边往事
  # 和菜头的微信Blog,用于分享各种新鲜资讯
  bitsea:
    cache_image: false
    output: true
  # ikanxue
  # 致力于移动与安全研究的开发者社区，看雪学院(kanxue.com)官方微信公众帐号。
  ikanxue:
    cache_image: false
    output: true
  # 婉如一勺
  # 弱水三千只要一勺
  likeyishao:
    cache_image: false
    output: true
  # 与食巨近以二会友
  # 珵嘻嘻(熊.二,middle name 不靠谱),与食巨近,贱多食广,五行缺肉,命里缺觉,好吃懒做,不学无术.178cm,牛津计算机女博土,去过50+国家,KO世遗控小组成员.With YWY.
  yierhuiyou:
    cache_image: true
    output: true
  # 艾格吃饱了
  # 关于食物，我不是比你懂得更多一些，只是比你花了更多的冤枉钱。
  aigechibaole:
    cache_image: false
    output: true
  # BetterRead
  # 有理、有趣、有用的英文读物推介。
  BetterRead:
    cache_image: false
    output: true
  # 笨上加笨
  # 您好，欢迎关注笨上加笨:)
  WulujiaNews:
    cache_image: false
    output: true
  # 半轻人
  # 王咏刚，笔名半轻人。技术宅，逻辑控。伪极客，真笨伯。用emacs写小说，用平水韵下酒。在太阳系最酷最大的网络公司上班，梦见二进制的下午茶。
  ban-qing-ren:
    cache_image: false
    output: true
  # 暴走看啥片儿
  # 史上最实惠、最接地气的影评节目！绝对是您居家旅行必备观影指南！
  baozoukspr:
    cache_image: false
    output: true
  # 比尔盖茨
  # 比尔·盖茨(BillGates)唯一官方公众号，分享他见过的人、读过的书和学到的功课，内容包括全球健康、能源创新、教育改革和读书笔记等。
  gatesnotes:
    cache_image: false
    output: true
  # 编辑之家
  # 无论媒体发展到什么程度，它都离不开我们编辑人的担当。编辑之家以编辑出版学专业为根基，倡导人人为编和编为人人的基本理念，集信息发布、资源推介，课程教学、专业研究、班级活动以及各类深度策划选题和话题探讨功能于一体。
  bnuzbjzj:
    cache_image: false
    output: true
  # 奔跑的楠子
  # 一个90后の自我养成记，想要和你一起变成更好的人！
  nanzimail:
    cache_image: false
    output: true
  # 不玩会死
  # 如果你爱玩，善玩，以玩自豪，欢迎入坑玩货群体。
  gh_68029851e270:
    cache_image: false
    output: true
  # ChesleaBurns
  # 多看，多说，多思考。
  gh_aa017d22f171:
    cache_image: true
    output: true
  # caoz的梦呓
  # caoz的心得与分享，只此一家，别无分号。
  caozsay:
    cache_image: false
    output: true
  # 程序人生
  # 十年漫漫程序人生，打过各种杂，也做过让我骄傲的软件；管理过数十人的团队，还带领一班兄弟姐妹创过业，目前在硅谷一家创业公司担任VP。关注程序人生，了解程序猿，学做程序猿，做好程序猿，让我们的程序人生精彩满满。
  programmer_life:
    cache_image: true
    output: true
  # 待字闺中
  # 深度分析大数据、深度学习、人工智能等技术，切中实际应用场景，为大家授业解惑。间或，也会介绍国内外相关领域有趣的面试题。
  daiziguizhongren:
    cache_image: false
    output: true
  # 大玩家张磊
  # 大玩家，讲述年轻人的旅行、消费和投资的话题，内容由作者张磊100%原创。如果你对银行、用卡、旅行、投资知识感兴趣，不妨跟大玩家一起体验一下高品质的生活。
  seniorplayer:
    cache_image: false
    output: true
  # 董老师在硅谷
  # 硅谷工程师，关注创业趋势，大数据，在线教育，社交自媒体。分享技术，体验职场，书写成长，欢迎交流，一起进步。
  donglaoshi-123:
    cache_image: false
    output: true
  # 嘀嗒嘀嗒
  # 感谢订阅，我是朱赟，也叫angela，很多人叫我安姐。硅谷AirbnbStaffEngineer。希望透过女码工的视角为您讲述硅谷技术人的故事和思考。
  AngelaTalk:
    cache_image: false
    output: true
  # 大鹏的小影集
  # 用照片记录生活
  photobystan:
    cache_image: false
    output: true
  # 二爷鉴书
  # 第一时间向大家推荐好书和介绍，同时坚决揭露烂书，以IT、互联网行业为主。个人品味，仅供参考。
  findbook:
    cache_image: false
    output: true
  # 峰瑞资本
  # FreeService,FreeStyle,FreeStartup,FreeSpirit.
  freesvc:
    cache_image: false
    output: true
  # 枫间语
  # 把最真实的世界，写给你看。
  gh_79f23be0596f:
    cache_image: false
    output: true
  # 飞总的IT世界面面观
  # 飞总，旅居西雅图的浙江人，IT人士，08年起从事大数据相关的基础构架的研究和开发，素爱读书，博闻强识，对计算机行业和前沿技术的发展有深刻和独到的见解，希望通过这个平台分享他关于IT世界的的心得体会。
  feiitworld:
    cache_image: false
    output: true
  # 风雪之隅
  # Laruence的个人订阅号
  StormCorner:
    cache_image: false
    output: true
  # 高可用架构
  # 高可用架构公众号。
  ArchNotes:
    cache_image: false
    output: true
  # 给产品经理讲技术
  # 为互联网产品经理普及技术基础知识
  pm_teacher:
    cache_image: false
    output: true
  # 硅谷观察
  # 周恒星的个人公众号。前驻硅谷科技记者，现乐视体育海外商务总监。偶尔发现感想，仅代表个人观点。
  guiguguancha:
    cache_image: false
    output: true
  # GrootSalon
  # 格鲁特分享
  GrootSalon:
    cache_image: false
    output: true
  # 硅谷周边
  # SiliconValleyNeighborhood.科技，读书，工作生活中引人深思的点滴。100%原创。
  svneighborhood:
    cache_image: false
    output: true
  # 坏时代
  # 这是最好的时代，也是最坏的时代。「小道消息」2.0版本。
  TheBadTime:
    cache_image: false
    output: true
  # 航班管家老机长
  # 专注于移动互联网从业者技术交流、职业发展，分析移动互联网最新发展趋势，提供最有价值的沙龙论坛。
  gh_ce7347f4401e:
    cache_image: false
    output: true
  # 酱油炒饭
  # 山那边的朋友们，你们好吗~~~
  LiWei_on_IT:
    cache_image: true
    output: true
  # 极简极浅
  # IT女工程师，写点简单浅显的技术文章。关注云计算，容器，微服务及DevOps技术，欢迎交流！
  noellachen:
    cache_image: true
    output: true
  # 架构师之路
  # 架构师之路，坚持撰写接地气的架构文章
  road5858:
    cache_image: false
    output: true
  # 跨界码农
  # 一个码农对技术、生活、管理、八卦的跨界闲聊。你的关注，即是我写作的动力。
  HiNotes:
    cache_image: true
    output: true
  # Kane的小K屋
  # 给朋友们分享俺的作品，希望给大家带来快乐
  KRoom01:
    cache_image: true
    output: true
  # 科学性
  # 科学性是丁香医生旗下的两性科普平台。有趣、有用、有料，和你一起科学地探索G点。我们将改变潮水的高度。
  sex-ology:
    cache_image: false
    output: true
  # keso怎么看
  # 科技，互联网，生活及其他
  kesoview:
    cache_image: false
    output: true
  # 氪TV
  # 36氪官方视频品牌
  krvideo:
    cache_image: false
    output: true
  # LateNews by 小晚
  # 取名「LateNews」是因为朋友们都叫我小晚。专业财经记者。支持创业、投资和自由竞争，反对垄断与黑幕。言语犀利，心怀善意。
  LateNews:
    cache_image: true
    output: true
  # Lightwing
  # 来自英国的三国迷中国通讲述不一样的视角看世界
  gh_9b1680a9f70c:
    cache_image: false
    output: true
  # 路上的光阴
  # 在路上和远方
  time_on_the_road:
    cache_image: true
    output: true
  # 乱槽之巅
  # 经常吐槽，偶尔分享
  luancaozhidian:
    cache_image: false
    output: true
  # 懒人在思考
  # 本懒号主要关注点：隐私、攻击、安全开发。从我们这，你至少可以知道当下黑客世界的另类视角。By余弦@LanT34m
  lazy-thought:
    cache_image: false
    output: true
  # 灵雀云
  # 灵雀云是中国第一家基于容器，服务于完整开发周期的新一代云平台。灵雀云以容器这个新一代应用交付件为中心，全方位支持云端应用创建、编译、集成、部署、运行的每一个环节。
  AlaudaCloud:
    cache_image: false
    output: true
  # 李开复
  #
  kaifu:
    cache_image: false
    output: true
  # 聊聊架构
  # 在这里煮酒聊架构。
  archtime:
    cache_image: false
    output: true
  # Microsoft认知服务
  # 微软认知服务（前牛津计划）认证公众号。分享认知服务提供的技术文档，演示，服务，应用精选，行业视野，及媒体动态。愿成为您的最强大脑，让智能服务触手可及。
  msprojectoxford:
    cache_image: false
    output: true
  # 默默大人
  # 微播江湖女主播默默私人分享，默默日常，默默吐槽，默默囧事私房照小小默大爆料。
  mmnwdr:
    cache_image: false
    output: true
  # 马文的文
  # 安静写作，焦虑思考。
  marvinsthought:
    cache_image: false
    output: true
  # Megvii旷视科技
  # 旷视(Face++)是一家以计算机视觉为核心的人工智能企业，致力于为行业型用户和个人型用户提供全方位的智能解决方案和智能数据服务。
  #megvii-tech: ### too many
  #  cache_image: false
  #  output: true
  # MacTalk
  # MacTalk开通于2012年末，内容起于Mac而不止Mac，内容覆盖了技术、创业、产品和人文思考。文风有趣，又有一点力量。相关图书《MacTalk·人生元编程》《MacTalk·跨越边界》
  sagacity-mac:
    cache_image: false
    output: true
  # OfferCome猎头
  # 专注于互联网、移动互联网的猎头资讯平台。
  gh_c8c6865b6d8a: ### too many
    cache_image: false
    output: true
  # 皮卡熊狂想曲
  # 网络天下之豪，集人类智慧之大乘，探索未知。目标高远，亦脚踏实地，且行且歌且思。不媚俗，不唯上，不趋时。
  pika-bear:
    cache_image: false
    output: true
  # 七牛云
  # 七牛云，开发者的互联网创新加速引擎。
  qiniutek:
    cache_image: false
    output: true
  # 奇舞周刊
  # 《奇舞周刊》是由奇舞团维护的前端技术周刊。每周五向大家推送前端技术文章。
  gh_ffb279ea1674:
    cache_image: false
    output: true
  # 趣火星
  # 大家好，我是许妙成，趣火星原来是我的创业项目，现在是我的个人blog，希望可以和大家分享一些和人文、科技、商业相关的信息。BP传送门：xumiaocheng@unityvc.com
  gohuoxing:
    cache_image: false
    output: true
  # 覃超帝国兴亡史
  # 覃超帝国兴亡史，在希望的田野上:如何去准备面试和去硅谷列强(Facebook,Google,LinkedIn,Airbnb,etc)工作；互联网创业；如何申请去北美计算机牛校（比如CMU,Stanford,etc）
  qc_empire:
    cache_image: false
    output: true
  # qing bao si cao
  # ignore due to it's empty
  # gh_d95a99307fdc:
  #   cache_image: false
  #   output: true
  # RTBChina
  # RTBChina是关于中国网络广告新生态系统的资讯精选。介绍DSP,SSP,AdExchange,DMP,和数据交易平台在中国发展状况。www.RTBChina.com编纂维护最新的《中国RTB广告技术产业地图》和行业研究报告
  RTBChina: ### too many
    cache_image: false
    output: true
  # 肉饼铺子
  # robbin是前JavaEye网站创始人，现在是丁香园CTO。如果你是技术人员，正在创业或者希望加入创业，关注互联网产品、研发、运营、创业管理，请关注我。
  robbinthoughts:
    cache_image: false
    output: true
  # 日食记
  # 温暖治愈你的心和胃。
  rishi-ji:
    cache_image: false
    output: true
  # 三表蛇门阵
  # 负责吐槽一切
  sanbiao66:
    cache_image: false
    output: true
  # 神秘的程序员们
  # 作为一个程序员星人，在地球上工作生活时，你是否会感到孤独呢？这里有来自程序员母星的亲切问候和地球漫游指南。国内首部以程序员文化、技术主题、项目管理及互联网创业的为主题漫画，诞生于09年。主创：西乔、霍炬。
  coderstory:
    cache_image: true
    output: true
  # 三表龙门阵
  # 负责吐槽一切！互联网大喷壶，大嘴善喷喷天下可喷之事！
  sanbiao1984:
    cache_image: false
    output: true
  # 十分钟读完一本书
  # 每月分享一本好书的浓缩版，如果觉得有意思，可以买来读一读。关注领域：商业、科技、心理学、个人成长、有效沟通等。
  Read_a_Book_a_Week:
    cache_image: false
    output: true
  # Spenser
  # Spenser:金融圈的职场老司机，世俗的伪文艺男中年，这里是60万城市新青年的思想聚集地
  spenserandhk: ### too many
    cache_image: false
    output: true
  # 省钱研究所
  # 更聪明的生活，更享受生活
  gh_dc406cf27249:
    cache_image: false
    output: true
  # 兽脑的世界
  # 野兽码字的地方
  zny918:
    cache_image: false
    output: true
  # 探索时间
  # 探索有趣的事，遇见有趣的人。
  tansuo-time:
    cache_image: false
    output: true
  # 腾讯
  # 腾讯公司唯一官方帐号。
  tencent: ### too many
    cache_image: false
    output: true
  # 天猫技术
  # 天猫技术-全球最懂商业的技术团队
  tmalltech:
    cache_image: false
    output: true
  # 微信派
  # 微信第一手官方活动信息发布，线下沙龙活动在线互动平台。独家分享微信公众平台优秀案例，以及权威专家的精彩观点。
  wx-pai: ### too many
    cache_image: false
    output: true
  # 微软小娜
  # 微软小娜（Cortana）是微软发布的全球第一款跨平台智能个人助理。关注即可及时了解最新技能更新，随时提供反馈建议，未来的人工智能将有你的智慧。
  MS_Cortana:
    cache_image: false
    output: true
  # 微软科技
  # 微软中国官方公众号
  mstech2014: ### too many
    cache_image: false
    output: true
  # 微软苏州
  # 微软苏州官方订阅号
  gh_4f5b80bdfe02:
    cache_image: false
    output: true
  # 王路在隐身
  # 发布文章。
  i_wanglu:
    cache_image: false
    output: true
  # 歪理邪说
  # 一切关于未来的故事在实现之前都是歪理邪说。
  wxieshuo:
    cache_image: false
    output: true
  # WeMobileDev
  # 微信移动客户端开发团队官号，分享微信在Android、iOS、Mac、Winphone、Windows等平台的开发经验、前沿技术，以及一些鲜为人知的小故事。
  WeMobileDev:
    cache_image: false
    output: true
  # 微软丹棱街5号
  # 微软亚太研发集团官方账号，也是微软与极客朋友们分享黑科技、互动交流的第一窗口。欢迎走进丹棱街5号，探索科技力量，感悟澎湃创新！
  Microsoft_ARD: ### too many
    cache_image: false
    output: true
  # 小道消息
  # 在这里，我想为你呈现一幅中国互联网的清明上河图。
  WebNotes:
    cache_image: false
    output: true
  # 徐瑾经济人
  # 阅读与分享：经济与人文的路口
  econhomo:
    cache_image: true
    output: true
  # 学习学习再学习
  # 通往财富自由之路
  xiaolai-xuexi:
    cache_image: false
    output: true
  # 学术鳖的烟酒僧活
  # 在西门以南南门以西有一群学术鳖，它们苦逼又逗比，它们学酥伪文艺，它们搬砖搬砖搬砖搬砖永远不停息。喔，秃头的学术鳖，喔，目害的学术鳖，它们自娱自乐误打误撞跌进了paper里，这才发现博士毕业只是在梦里~
  xueshubie:
    cache_image: true
    output: true
  # 鱼肚白动画
  # 了解全球动画咨询，分享更多动画知识、经验、技巧，做一流动画师！我们是北京鱼肚白文化传媒有限公司。欢迎关注我们的原创动画《女生宿舍日常》
  wangbinnv09:
    cache_image: false
    output: true
  # 悠然间
  # 素食、教育、国际象棋、瑜伽、科技、音乐、茶……分享悠然生活，欢迎随时转转
  Rosetime_thu:
    cache_image: false
    output: true
  # 余晟以为
  # 我是这么以为的，当然你也可以那么以为
  yurii-says:
    cache_image: false
    output: true
  # 夜航船Northfleet
  # 我们真实可感，躲无可躲的生活。
  northfleet: ### too many
    cache_image: false
    output: true
  # 移动开发前线
  # 专注于分享移动开发前沿和一线技术。
  bornmobile: ### too many
    cache_image: false
    output: true
  # 终端安全那些事儿
  # 关注、分享终端安全。
  zhongduananquan:
    cache_image: false
    output: true
  # 左手单反右手键盘
  # legendlin的个人小站
  camera_keyboard:
    cache_image: true
    output: true
  # 职场沐心
  # 在世界500强IT公司摸爬滚打10余年，同时身为孩子的母亲，深知一个职场女性的不易与艰辛。在人生求索的路上，愿与各位职场女性一同探讨，一同成长。浴心而美，重新而美！
  zhichangyuxin:
    cache_image: true
    output: true
  # 征信小助手
  # 分享、传播征信知识
  zgzxxzs:
    cache_image: false
    output: true
  # 301在路上
  # 着重宣传企业和个人信息安全意识，帮助大家更好地保护自己。
  a301zls:
    cache_image: false
    output: true
